name: settleup
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.7
  image_picker: ^0.8.7+5
  shared_preferences: ^2.1.1
  firebase_core: ^4.2.1      
  firebase_auth: ^6.1.1      
  cloud_firestore: ^6.0.3   
  firebase_storage: ^13.0.4
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
